### ISSUE TITLE
Telegram should not be on this list.

### ISSUE THREAD

**Issue by mansguiche** [r00ster91/shifting#2]
Telegram is not privacy focused. They claim to be but it seems to be a marketing tactic. In [this article](https://hongkongfp.com/2020/07/05/exclusive-telegram-to-temporarily-refuse-data-requests-from-hong-kong-courts-amid-security-law-terrorism-row/)  they seem to be doing a good thing by refusing data request to the Hong Kong police but it also shows that in normal circumstances they do comply with police data requests. This would not be possible if they encrypted their messages by default which they do not. 

I would recommend removing it from this list

**Comment by r00ster91** [comment]
I have read a bit more into it and I agree to removing it.
