### ISSUE TITLE
yotter is a good YouTube proxy

### ISSUE THREAD

**Issue by mansguiche** [r00ster91/shifting#4]
https://github.com/ytorg/Yotter

Yotter is very similar to invidious but built in python which makes it more attractive for developers to contribute to. It's still in its early stages but works well and has more features coming soon.

P.s. sorry for making issues instead of pull requests, I'm on mobile and this is much easier :)

**Comment by r00ster91** [comment]
Looks interesting. I'd say we wait for it to mature first and then it can be added at some point. I have added it as a comment to make sure it's not forgotten.
